##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

NAME =	libmy.a

all:	$(NAME)

$(NAME):
	@echo -e "\033[1;31mJ'ai la flemme (⩾﹏⩽)....\033[0;39m"
	gcc -c *.c
	ar rc $(NAME) *.o
	@echo -e "\033[1;35mMais tkss c'est bien psq c toi <3( ˘ ³˘)♥\033[0;39m"

clean:
	rm -f *.o
	rm -f $(NAME)
	rm -f ../$(NAME)

re: clean all